# Generated by Django 5.0 on 2023-12-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='UserProfile.teacheruserprofile'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='UserProfile.studentuserprofile'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded', to='UserProfile.teacheruserprofile'),
        ),
        migrations.AddField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.teacheruserprofile'),
        ),
        migrations.AddField(
            model_name='program',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Academic.academicsession'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Academic.department'),
        ),
        migrations.AddField(
            model_name='period',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.program'),
        ),
        migrations.AddField(
            model_name='section',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.program'),
        ),
        migrations.AddField(
            model_name='period',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.section'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.program'),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester'),
        ),
        migrations.AddField(
            model_name='period',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester'),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.period'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='UserProfile.studentuserprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester'),
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.subject'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='UserProfile.teacheruserprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('program_id', 'academic_session', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('semester', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('program', 'semester', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('program', 'semester', 'section', 'date', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'semester', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('date', 'teacher')},
        ),
    ]
