# Generated by Django 4.2.7 on 2023-12-09 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('session', models.PositiveSmallIntegerField(choices=[(1, 'Session 1'), (2, 'Session 2'), (3, 'Session 3'), (4, 'Session 4'), (5, 'Session 5'), (6, 'Session 6'), (7, 'Session 7'), (8, 'Session 8'), (9, 'Session 9'), (10, 'Session 10')], verbose_name='session')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.program')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('program', 'semester', 'section', 'date', 'session')},
            },
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, default=1, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Late'), (4, 'Leave')], verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'user')},
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Present'), (2, 'Absent')], verbose_name='status')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='period',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
